export const ERROR_CODES = {
  NOT_FOUND: 'NOT_FOUND',
  DUPLICATE: 'DUPLICATE',

  // AUTH
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',

  // VALIDATION
  VALIDATION_ERROR: 'VALIDATION_ERROR',

  // SYSTEM
  INTERNAL_ERROR: 'INTERNAL_ERROR',
};
