TRUNCATE TABLE users RESTART IDENTITY CASCADE;

TRUNCATE TABLE auth RESTART IDENTITY CASCADE;

TRUNCATE TABLE products RESTART IDENTITY CASCADE;

TRUNCATE TABLE carts RESTART IDENTITY CASCADE;

TRUNCATE TABLE cart_items RESTART IDENTITY CASCADE;

TRUNCATE TABLE orders RESTART IDENTITY CASCADE;

TRUNCATE TABLE order_items RESTART IDENTITY CASCADE;

TRUNCATE TABLE inventory RESTART IDENTITY CASCADE;

TRUNCATE TABLE payments RESTART IDENTITY CASCADE;
