version: '3.9'
name: ecom-mono
services:
  api:
    image: ecom-mono
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: production
    ports:
      - '3000:3000'
    env_file:
      - ../.env
    environment:
      - HOST=0.0.0.0
      - DB_URL=postgresql://ecom_app:devpw@postgres:5432/ecom_mono
    networks:
      - ecom-network
    restart: unless-stopped

networks:
  ecom-network:
    external: true
