### POST REGISTER
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "email": "user2000@example.com",
  "password": "111111",
  "full_name": "user2001"
}

### POST LOGIN
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "user2000@example.com",
  "password": "111111"
}
