######################## PRODUCT #############################
@page=3
@cursor = eyJjcmVhdGVkX2F0IjoiMjAyNi0wNC0xN1QwNzo1NzoyOC41MDFaIiwiaWQiOiJhMjE0ZTZmZi03ZGFmLTQ3ZWItOWM4OC00Y2FiMzNmOGI4YTkifQ==
@id = 

### GET
GET {{baseUrl}}/products

### default pagination
GET {{baseUrl}}/products
?page={{page}}

### pagination use cursor
GET {{baseUrl}}/products
?cursor={{cursor}}

### POST
POST {{baseUrl}}/products
Content-Type: application/json

{
  "name": "iPhone",
  "price": 1000,
  "stock": 5
}

### UPDATE
PUT {{baseUrl}}/products/{{id}}
Content-Type: application/json

{
  "name": "iPhone 15 Pro",
  "price": 1200,
  "stock": 10
}

### DELETE
DELETE {{baseUrl}}/products/{{id}}
