######################## PRODUCT #############################
@limit = 10
@offset = 20
@created_at = 2026-04-17T07:57:28.501Z
@id= a214e6ff-7daf-47eb-9c88-4cab33f8b8a9

### GET
GET {{baseUrl}}/products

### default pagination
GET {{baseUrl}}/products
?limit={{limit}}&offset={{offset}}

### pagination use cursor
GET {{baseUrl}}/products
?created_at={{created_at}}
&id={{id}}

### POST
POST {{baseUrl}}/products
Content-Type: application/json

{
  "name": "iPhone",
  "price": 1000,
  "stock": 5
}

### UPDATE
PUT {{baseUrl}}/products/0d1b57b0-03c3-4617-89f4-3bb1c4de7d46
Content-Type: application/json

{
  "name": "iPhone 15 Pro",
  "price": 1200,
  "stock": 10
}

### DELETE
DELETE {{baseUrl}}/products/{{id}}
