name: PR Validation

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  validate-pr:
    runs-on: ubuntu-latest

    steps:
      # --------------------------------
      # Setup
      # --------------------------------
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # --------------------------------
      # CI
      # --------------------------------
      - name: CI
        run: make ci
